Update installer

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -3,13 +3,83 @@
 <?php
 
 /**
- * Migrate
+ * Install
  * 
- * Migration handler to build/install tables.
+ * Installer handler to build tables.
+ * Dependency : PHP Mysqli Extension.
  * 
  * @author Gemblue
  */
 
 require_once __DIR__ . '/../src/Config/database.php';
 
-var_dump($config);
+// Ascii Banner
+echo "
+_____                  _       _         _    _           _   
+(_   _)_               ( )  _  ( )       (_ ) (_ )        ( )_ 
+  | | (_)  ___   _   _ | | ( ) | |   _ _  | |  | |    __  | ,_)
+  | | | |/' _ `\( ) ( )| | | | | | /'_` ) | |  | |  /'__`\| |  
+  | | | || ( ) || (_) || (_/ \_) |( (_| | | |  | | (  ___/| |_ 
+  (_) (_)(_) (_)`\__, |`\___x___/'`\__,_)(___)(___)`\____)`\__)
+                ( )_| |                                        
+                `\___/'                                        
+\n\n";
+
+// Create connection.
+$connection = mysqli_connect($config['host'], $config['username'], $config['password'], $config['database']);
+
+// Prepare SQL
+$table[0] = "CREATE TABLE `wallet` (
+  `id` int(11) NOT NULL AUTO_INCREMENT,
+  `subject_id` int(10) NOT NULL,
+  `balance` int(10) NOT NULL,
+  `created_at` datetime NOT NULL,
+  `updated_at` datetime NOT NULL,
+  PRIMARY KEY (`id`)
+) ENGINE=InnoDB DEFAULT CHARSET=latin1";
+
+$table[1] = "CREATE TABLE `wallet_ledger` (
+  `id` int(10) NOT NULL AUTO_INCREMENT,
+  `subject_id` int(10) NOT NULL,
+  `transaction_id` int(10) NOT NULL,
+  `amount` float NOT NULL,
+  `entry` varchar(10) NOT NULL,
+  `created_at` datetime NOT NULL,
+  `updated_at` datetime DEFAULT NULL,
+  PRIMARY KEY (`id`)
+) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
+
+$table[2] = "CREATE TABLE `wallet_transaction` (
+  `id` int(11) NOT NULL AUTO_INCREMENT,
+  `subject_id` int(10) NOT NULL,
+  `type` varchar(20) NOT NULL,
+  `currency` varchar(3) NOT NULL,
+  `amount` int(10) NOT NULL,
+  `code` varchar(10) NOT NULL,
+  `metadata` varchar(100) NOT NULL,
+  `created_at` datetime NOT NULL,
+  `updated_at` datetime DEFAULT NULL,
+  `deleted_at` datetime DEFAULT NULL,
+  PRIMARY KEY (`id`)
+) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
+
+$table[3] = "CREATE TABLE `wallet_transaction_log` (
+  `id` int(11) NOT NULL AUTO_INCREMENT,
+  `transaction_id` int(11) NOT NULL,
+  `status` varchar(30) NOT NULL,
+  `created_at` datetime NOT NULL,
+  `expired_at` datetime DEFAULT NULL,
+  PRIMARY KEY (`id`)
+) ENGINE=InnoDB DEFAULT CHARSET=latin1;
+";
+
+$i = 0;
+for($i=0; $i<=3; $i++) {
+    $execution = mysqli_query($connection, $table[$i]);
+}
+
+if ($execution) {
+    echo "Congratulations, installation done!\n\n";
+} else {
+    echo "Failed, please check the database configuration!.\n\n";
+}
